#!/bin/sh
# vim:ft=bash
# 01-misc
# shellcheck enable=all
command -v shopt >/dev/null && shopt -u cmdhist
umask 7
PATH="/npbin:${PATH}:${HOME}/.local/bin:${HOME}/.local/bin/*:."
export PATH
LS_COLORS="st=30;4${COL0}:no=3${COL1}:fi=1;3${COL1}:rs=0:di=3${COL0};1:ln=3${COL0};2:ex=1;3${COL2}:"
export LS_COLORS
WWW_HOME='http://lite.duckduckgo.com/lite/'
export WWW_HOME
alias :q='exit'
alias clear='printf "[H[3J";\clear;echo "[38;2;245;169;184mby using this terminal you agree to the TOS and Privacy Policy[0m"'
