#!/bin/sh
launch(){
	DISPLAY=:0
	export DISPLAY
	for x in "$@"; do
		file=""
		for y in "${HOME}/.local/share/applications" "/usr/share/applications" "/var/lib/flatpak/exports/share/applications"; do
			[ -f "${y}/${x}.desktop" ] && file="${y}/${x}.desktop"
		done
		if [ -z "${file}" ]; then
			echo "ERROR: app \"${x}\" not found!"
		else
			dex "${file}" >/dev/null 2>&1
		fi
	done
}
export launch
