#!/bin/sh
# vim:ft=bash
# 01-common
# shellcheck enable=all
shopt -u cmdhist
shopt -s checkwinsize
umask 7
PATH="/npbin:${PATH}:${HOME}/.local/bin:${HOME}/.local/bin/*:."
export PATH
LS_COLORS="st=30;4${COL0}:no=3${COL1}:fi=1;3${COL1}:rs=0:di=3${COL0};1:ln=3${COL0};2:ex=1;3${COL2}:"
export LS_COLORS
WWW_HOME='http://lite.duckduckgo.com/lite/'
export WWW_HOME
