#!/bin/sh
# 11-btrls
# shellcheck enable=all
alias ls=btrls
btrls(){
	temp=""
	for x in "$@"; do
		t="$(echo "${x}" | sed -E 's|^-(\w*)a|-\1A|g;s| |\ |g;s|^-(\w*)l|-\1gGh|g' || true)"
		[ -z "${temp}" ] && temp="${t}" || temp="${temp}ə${t}"
	done
	IFS="ə";
	#shellcheck disable=SC2086
	\ls ${_ls_extra:-} --color=auto ${temp}
}
export btrls
