#!/bin/sh
app="$(/home/.config/i3/dmenu_path | dmenu -i -sb \#f5a9b8 -sf \#ffffff -nb \#5bcefa -nf \#005fff | /home/.config/i3/post_dmenu)"
if [ -z "$app" ]; then
	exit
fi
echo dex "$app" | xargs i3-msg -- exec --no-startup-id
